root = "."
tmp_dir = "build"

[build]
  cmd = "cmake -B build -S src -DCMAKE_EXPORT_COMPILE_COMMANDS=ON && cmake --build build"
  bin = "build/keyboard"
  full_bin = "./build/keyboard"
  rerun = false
  args_bin = []
  delay = 1000
  exclude_dir = ["build", "things"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  include_dir = []
  include_ext = ["c", "cc", "cpp", "h", "hpp"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
